### PR TITLE
82 fix questionscontrollerdestroy

### LINKED ISSUE #82: Fix QuestionsController#destroy
QuestionsController#destroy is failing on line 13 `question.destroy!` with a one off error. For example when destroying Question.find(103) we get a foreign key constraint error for question id 104

```
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "questions" violates foreign key constraint "fk_rails_0721413afc" on table "taggings"
DETAIL:  Key (id)=(104) is still referenced from table "taggings".
```

### PR DESCRIPTION
**Pull request by Strompy**
## Description

- Adds logic to QuestionsController#destroy to check if the question is a parent. If question is a parent, it will set a flash message and not attempt a destroy to avoid issues with the children's dependencies. If it is a child, or has no children, it will be destroyed and set a successful flash message.
- Moves the flash message container to the application.html
- Updates Question dependencies to destroy has_many records but not belongs_to records

#### Success Message
Screenshot 2023-04-16 at 12 02 28 PM

#### Error message
Screenshot 2023-04-16 at 12 03 00 PM

## Issue(s)
Closes #82

### CODE REVIEW

File: app/controllers/admin/dashboard/questions_controller.rb [hunk 1]
```diff
@@ -7,9 +7,13 @@ def index
...
-        question.destroy!
+        if !question.children.empty?
+          flash[:error] =
+            "Question ##{question.id} has children questions and cannot be deleted. Please remove questions with parent ##{question.id} first and then try again."
+        else
+          question.destroy!
+          flash[:success] = "Successfully deleted question ##{question.id}"
+        end
 
         redirect_to admin_dashboard_questions_path
```
Comment (Strompy) [inline app/controllers/admin/dashboard/questions_controller.rb:18]: That better for you Henry? 😂

File: app/controllers/admin/dashboard/questions_controller.rb [hunk 2]
```diff
@@ -7,11 +7,14 @@ def index
 
       def destroy
         question = Question.find(params['id'])
-        question.taggings.destroy_all
-        question.questionnaires.destroy_all
-        question.destroy!
+        if !question.children.empty?
```
[the remark this answers is not in the document]
Comment (Strompy) [reply app/controllers/admin/dashboard/questions_controller.rb:10]: Good call. That is cleaner

File: app/controllers/admin/dashboard/questions_controller.rb (hunk 1 above)
Comment (HenryHaller) [reply app/controllers/admin/dashboard/questions_controller.rb:18]: yes
